---
- hosts: webserver
  become: true
  become_user: root
  roles:
    - role: apache
      tags:
        - apache
    - role: php
      tags:
        - php
    - role: mysql
      tags:
        - mysql
    - role: wordpress
      tags:
        - wordpress
